# Generated by Django 5.2.1 on 2025-05-15 18:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('available_margin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('risk', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=100)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=5)),
                ('leverage', models.IntegerField()),
                ('trigger_price', models.DecimalField(decimal_places=12, default=0.0, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=12, max_digits=20)),
                ('stop_price', models.DecimalField(decimal_places=12, max_digits=20)),
                ('take_profit_prices', models.JSONField(default=list)),
                ('cancel_levels', models.JSONField(default=list)),
                ('move_stop_after', models.IntegerField()),
                ('primary_volume', models.DecimalField(decimal_places=12, max_digits=20)),
                ('current_volume', models.DecimalField(decimal_places=12, max_digits=20)),
                ('fill_history', models.JSONField(default=list)),
                ('last_status', models.CharField(max_length=50)),
                ('breakeven', models.BooleanField(default=False)),
                ('pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=8, max_digits=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading_buddy.account')),
            ],
        ),
    ]
