# Generated by Django 5.2.1 on 2025-06-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='last_status',
            field=models.CharField(default='NEW', max_length=50, null=True),
        ),
    ]
