# Generated by Django 5.2.7 on 2025-10-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='server_position_id',
            field=models.CharField(null=True),
        ),
    ]
