# Generated by Django 5.2.1 on 2025-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_margin',
        ),
        migrations.AddField(
            model_name='account',
            name='available_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
