# Generated by Django 5.2.1 on 2025-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0002_alter_position_last_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='commission_usd',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl_usd',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Net profit, after commissions', max_digits=20),
        ),
    ]
