# Generated by Django 5.2.1 on 2025-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0002_remove_user_available_margin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='available_margin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='risk',
        ),
        migrations.AddField(
            model_name='user',
            name='risk_percent',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
