# Generated by Django 5.2.7 on 2025-10-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0002_position_server_position_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='current_volume',
            new_name='max_held_volume',
        ),
    ]
