# Generated by Django 5.2.7 on 2025-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0003_rename_current_volume_position_max_held_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current_volume',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
