# Generated by Django 5.2.1 on 2025-06-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0004_user_current_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='commission_usd',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Trading fees, is always negative', max_digits=20),
        ),
    ]
