# Generated by Django 5.2.7 on 2025-10-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0004_position_current_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='secret_key',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_volume',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=20),
        ),
    ]
