# Generated by Django 5.2.1 on 2025-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0005_alter_position_commission_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='commission_usd',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Trading fees, is always negative, though theoretically could be positive due to funding fees', max_digits=20),
        ),
    ]
