# Generated by Django 5.2.7 on 2025-10-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0005_alter_account_api_key_alter_account_secret_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='start_time',
            field=models.DateTimeField(help_text='The moment primary order of position was placed', null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='start_time',
            field=models.DateTimeField(help_text='The moment primary order of position was placed', null=True),
        ),
    ]
