# Generated by Django 5.2.7 on 2026-03-01 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0006_alter_position_start_time_alter_trade_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='move_stop_after_rr',
            field=models.DecimalField(decimal_places=12, help_text='After which risk reward level move stop-loss to entry level, this variable holds reward value from the ratio', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_usd',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
