# Generated by Django 5.2.7 on 2026-05-03 11:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0007_position_move_stop_after_rr_alter_trade_risk_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_setup',
            field=models.CharField(blank=True, choices=[('ACC_BORDER_BREAKTHROUGH', '(Ре)накопление - Пробой верхней границы'), ('ACC_BORDER_RETEST', '(Ре)накопление - Ретест верхней границы'), ('ACC_CREEK_BREAKTHROUGH', '(Ре)накопление - Пробой крика'), ('ACC_CREEK_RETEST', '(Ре)накопление - Ретест крика'), ('ACC_SPRING', '(Ре)накопление - Спринг'), ('DISTR_BORDER_RETEST', '(Ре)дистрибьюция - Ретест нижней границы'), ('DISTR_ICE_RETEST', '(Ре)дистрибьюция - Ретест льда'), ('DISTR_UPTHRUST', '(Ре)дистрибьюция - Аптраст'), ('BEAR_WOLFE', 'Медвежий Вульф'), ('BULL_WOLFE', 'Бычий Вульф'), ('DOWN_WEDGE_BREAKTHROUGH', 'Нисходящий клин - пробой верхней границы'), ('DOWN_WEDGE_RETEST', 'Нисходящий клин - ретест верхней границы'), ('UP_WEDGE_BREAKTHROUGH', 'Восходящий клин - пробой нижней границы'), ('UP_WEDGE_RETEST', 'Восходящий клин - ретест нижней границы'), ('DOWN_CHANNEL_REBOUND', 'Нисходящий канал - отбой вниз от верхней границы'), ('DOWN_CHANNEL_BREAKTHROUGH', 'Нисходящий канал - пробой верхней границы'), ('DOWN_CHANNEL_RETEST', 'Нисходящий канал - ретест верхней границы'), ('UP_CHANNEL_REBOUND', 'Восходящий канал - пробой нижней границы'), ('UP_CHANNEL_BREAKTHROUGH', 'Восходящий канал - ретест нижней границы'), ('UP_CHANNEL_RETEST', 'Восходящий канал - отбой вверх от нижней границы'), ('SECANT_RETEST', 'Ретест секущей в шорт'), ('DOWN_TRENDLINE_REBOUND', 'Отбой вниз от нисходящей трендовой'), ('UP_TRENDLINE_REBOUND', 'Отбой вверх от восходящей трендовой')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='risk_percent',
            field=models.DecimalField(decimal_places=7, default=3.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_percent',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='risk_usd',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
