# Generated by Django 5.2.7 on 2026-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_buddy', '0008_trade_tags_trade_trade_setup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='tags',
        ),
        migrations.AlterField(
            model_name='account',
            name='exchange',
            field=models.CharField(choices=[('BingX', 'BingX'), ('ByBit', 'ByBit'), ('Investing', 'Investing')], max_length=120),
        ),
    ]
